# https://gohugo.io/getting-started/configuration/#configure-minify

disableCSS   = true
disableHTML  = false
disableJS    = true
disableJSON  = false
disableSVG   = false
disableXML   = false
minifyOutput = true

[tdewolff]

  [tdewolff.css]
  keepCSS2  = true
  precision = 0

  [tdewolff.html]
  keepComments            = false
  keepConditionalComments = true
  keepDefaultAttrVals     = true
  keepDocumentTags        = true
  keepEndTags             = false
  keepQuotes              = false
  keepWhitespace          = false

  [tdewolff.js]
  keepVarNames = false
  precision    = 0

  [tdewolff.json]
  keepNumbers = false
  precision   = 0

  [tdewolff.svg]
  precision = 0

  [tdewolff.xml]
  keepWhitespace = false
