# Google Analytics
googleAnalytics  = "" # https://analytics.google.com/analytics/web/#/a124176424w182560743p180239535/admin/tracking/tracking-code/

# Meta
title               = "devsec.tools"
description         = "Security and reliability tooling — by software engineers, for software engineers."
domain              = "devsec.tools"
gravatar_4x         = "https://media.githubusercontent.com/media/northwood-labs/branding/refs/heads/main/gravatar-white-square-512.png"
iso8601             = "2006-01-02T15:04:05-07:00"
locale              = "en_US"
recent_posts_number = 5
templateDebugger    = false

# OEmbed images
defaultOembed   = ""
oembedMediaType = ""
oembedWidth     = 0
oembedHeight    = 0
oembedAlt       = ""

# Other settings
copyrightStart  = "2024"
copyrightEntity = "Northwood Labs"
copyrightURL    = "https://northwood-labs.com"
footerLogo      = "https://github.com/northwood-labs/branding/raw/refs/heads/main/NWL-Simplified-Horizontal-Color.svg"
footerStatement = "Security and reliability tooling — by software engineers, for software engineers."
metaTags        = "http, tls, http testing, tls testing, security testing, devsecops, devsec"
