# https://gohugo.io/getting-started/configuration/#configure-server

[[headers]]
for = '/**'
  [headers.values]
  Access-Control-Allow-Origin = "*"
  # Content-Security-Policy     = 'script-src localhost:1313 devsec.local devsec.local:1313; style-src localhost:1313 devsec.local devsec.local:1313'
  Referrer-Policy             = 'strict-origin-when-cross-origin'
  X-Content-Type-Options      = 'nosniff'
  X-Frame-Options             = 'DENY'
  X-XSS-Protection            = '1; mode=block'
